# Generated by Django 3.2.5 on 2021-07-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_rename_category_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
    ]
